# Generated by Django 4.2.7 on 2023-11-06 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import story.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='스토리 제목')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('bookmark', models.ManyToManyField(blank=True, related_name='bookmark_stories', to=settings.AUTH_USER_MODEL, verbose_name='북마크')),
                ('hate', models.ManyToManyField(blank=True, related_name='hate_stories', to=settings.AUTH_USER_MODEL, verbose_name='싫어요')),
                ('like', models.ManyToManyField(blank=True, related_name='like_stories', to=settings.AUTH_USER_MODEL, verbose_name='좋아요')),
            ],
            options={
                'verbose_name_plural': 'stories',
                'db_table': 'story',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField(verbose_name='문단')),
                ('image', models.ImageField(upload_to=story.models.story_image_upload_path, verbose_name='문단 이미지')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='story.story', verbose_name='작성자')),
            ],
            options={
                'db_table': 'content',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='댓글 내용')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.story', verbose_name='스토리')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
