# Generated by Django 4.2.7 on 2023-11-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0005_remove_story_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="like_count",
            field=models.PositiveIntegerField(default=0, verbose_name="좋아요 개수"),
        ),
    ]
