# Generated by Django 4.2.7 on 2023-11-30 08:54

from django.db import migrations, models
import story.models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_story_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, upload_to=story.models.story_image_upload_path, verbose_name='문단 이미지'),
        ),
    ]
