# Generated by Django 4.2.7 on 2023-11-06 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='이메일')),
                ('password', models.CharField(max_length=500, verbose_name='비밀번호')),
                ('nickname', models.CharField(max_length=30, unique=True, verbose_name='활동 아이디')),
                ('country', models.CharField(choices=[('대한민국', '대한민국'), ('미국', '미국'), ('프랑스', '프랑스'), ('스페인', '스페인'), ('일본', '일본'), ('중국', '중국')], max_length=50, verbose_name='국가')),
                ('profile_img', models.ImageField(blank=True, default='user/default_profile.jpg', upload_to='user/%Y/%m/', verbose_name='프로필 이미지')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자 여부')),
                ('is_active', models.BooleanField(default=True, verbose_name='계정 활성화 여부')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'db_table': 'claim',
            },
        ),
    ]
