# Generated by Django 4.2.7 on 2023-11-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='계정 활성화 여부'),
        ),
    ]
