# Generated by Django 4.2.7 on 2023-11-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_remove_story_hidden'),
        ('user', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recently_stories',
            field=models.ManyToManyField(blank=True, related_name='recently_stories', to='story.story'),
        ),
    ]
