# Generated by Django 4.2.7 on 2023-11-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userstorytimestamp_remove_user_recent_stories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstorytimestamp',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time Stamp'),
        ),
    ]
