# Generated by Django 4.2.7 on 2023-11-27 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userstorytimestamp_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_email', models.EmailField(max_length=255, verbose_name='구매자 이메일')),
                ('buyer_name', models.CharField(max_length=30, verbose_name='구매자 아이디')),
                ('name', models.CharField(max_length=30, verbose_name='구매 상품명')),
                ('paid_amount', models.PositiveBigIntegerField(verbose_name='결제 금액')),
                ('currency', models.CharField(max_length=30, verbose_name='통화')),
                ('pg_provider', models.CharField(max_length=30, verbose_name='결제 게이트웨이 제공자')),
                ('pg_tid', models.TextField(verbose_name='결제 ID')),
                ('pay_method', models.CharField(max_length=30, verbose_name='결제 방법')),
                ('bank_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='은행명')),
                ('card_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='카드명')),
                ('card_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='카드 번호')),
                ('receipt_url', models.URLField(blank=True, null=True, verbose_name='영수증 url')),
                ('status', models.CharField(max_length=30, verbose_name='처리 상태')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golden_ticket', models.PositiveIntegerField(default=1, verbose_name='골드 티켓')),
                ('silver_ticket', models.PositiveIntegerField(default=2, verbose_name='실버 티켓')),
                ('pink_ticket', models.PositiveBigIntegerField(default=10, verbose_name='핑크 티켓')),
                ('ticket_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
