# Generated by Django 4.2.7 on 2023-11-30 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_country'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paymentresult',
            table='payment result',
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='ticket',
        ),
    ]
