# Generated by Django 4.2.7 on 2023-12-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_paymentresult_table_alter_ticket_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='pink_ticket',
            field=models.PositiveIntegerField(default=10, verbose_name='핑크 티켓'),
        ),
    ]
