# Generated by Django 4.2.7 on 2023-12-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_ticket_pink_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstorytimestamp',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Time Stamp'),
        ),
    ]
