# Generated by Django 5.0 on 2023-12-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_userstorytimestamp_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentresult',
            name='currency',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='통화'),
        ),
        migrations.AlterField(
            model_name='paymentresult',
            name='paid_amount',
            field=models.PositiveIntegerField(verbose_name='결제 금액'),
        ),
        migrations.AlterField(
            model_name='paymentresult',
            name='pg_tid',
            field=models.TextField(blank=True, null=True, verbose_name='결제 ID'),
        ),
    ]
